config/routes.rb
Sage::Application.routes.draw do

  resources :projects do

    resources :digital_objects do
      member do
        post 'add_concept'
        post 'add_created_concept'
        post 'remove_concept'
      end

      collection do
        post 'import_drive_folder'
      end
    end

    resources :concepts do
      member do
        post 'add_object'
        post 'remove_object'
      end
    end

    member do
      get 'statistics'
      get 'import_annotations'
      post 'import_annotations'
      get 'export_annotations'
      post 'export_annotations'
      post 'generate_key'
      post 'reset_key'
      post 'remove_user'
    end

    collection do
      get 'redeem_key'
      post 'check_key'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
    end
  end

  root "site#welcome"

  get "/welcome" => "site#welcome"
  get "/application" => "site#application"
  get "/about" => "site#about"
  get "/participant_information" => "site#participant_information"

  get "/receive_oauth2" => "projects#receive_oauth2"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_roles, dependent: :destroy
  has_many :projects, through: :user_roles
  has_many :annotations

  before_destroy :orphan_annotations

  # Regular expression for email validation.
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  # Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX

  # Ensure the user has a secure password.
  has_secure_password

  private

  # Orphan all annotations created by this user.
  def orphan_annotations
    Annotation.where(user_id: id).each do |annotation|

      # Orphan annotation, but allow it to continue to exist.
      annotation.update(user_id: nil)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_access

  # GET /users
  # GET /users.json
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # Check participation details were set.
    if (params[:participant_information] && params[:participation] && params[:age])
      respond_to do |format|
        if @user.save

          # Log in as new user.
          session[:user_id] = @user.id

          format.html { redirect_to projects_path, notice: "Welcome aboard! Now
            that you've registered, you may wish to create a project, or redeem
            a key you've been provided. You can do that from here. Think of this
             page as your control center, it can be reached at any time by
             pressing the Projects link in the top bar." }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      @user.errors[:base] << "Please confirm your participation details."
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /users/login
  # POST /users/login
  def login

    # Check for the type of request.
    if request.get?

      # Initial request to login. Provide form.
      @user = User.new
    else
      # Check details in form and determine if the user will be logged in.

      # See if the provided email address exists.
      @user = User.find_by email: params[:user][:email]

      # Check password, if user exists.
      if !@user.nil? && (@user.authenticate params[:user][:password])

        # User exists and password is correct. Log in.
        flash[:notice] = "You have successfully logged in."
        session[:user_id] = @user.id

        # Redirect to the user's project page.
        redirect_to projects_path
      else

        # Incorrect password, or the user doesn't exist. Back to login page.
        @user = User.new
        @user.errors[:base] << "Incorrect email address or password."
      end
    end
  end

  # GET /users/logout
  def logout

    # Reset the session.
    reset_session

    # Redirect to main page.
    redirect_to "/"
  end

  private

    # Check authorisation before access.
    def check_access

      # Define public pages.
      public_pages = ["new", "create", "login", "logout"]

      # Allow user to access public pages.
      if public_pages.include? params[:action]
        return true
      end

      # Check if the user is logged in.
      if !@user
        flash[:notice] = "You are not logged in. Please log in to continue."
        redirect_to login_users_path
        return false
      end

      # Define private pages.
      private_pages = ["show", "edit", "update", "destroy"]

      # Allow the user to access private user pages.
      if (private_pages.include? params[:action]) && (@user.id.to_s.eql? params[:id])
        return true
      end

      # Otherwise, no permissions.
      redirect_to "/403.html"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :email, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :password, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <% if @user.new_record? %>

    <br>

    <p>
      Please read the <a href="/participant_information" target="_blank"> Information Sheet For Participants</a> before responding to the following questions.
    </p>

    <div class="field">
      <%= check_box_tag :participant_information, class:"col-md-2" %>
      <%= label_tag(:participant_information, "I have read the information contained in the Information Sheet For Participants.") %>
    </div>

    <div class="field">
      <%= check_box_tag :participation  %>
      <%= label_tag(:participation, "I agree to participate in this activty, understanding that I may withdraw at any time.") %>
    </div>

    <div class="field">
      <%= check_box_tag :age  %>
      <%= label_tag(:age, "I am over 18 years of age.") %>
    </div>

  <% end %>

  <div class="actions text-center">
    <%= link_to yield(:back_path) do %><div class="btn btn-default">
      <span class="glyphicon glyphicon-arrow-left"></span> Back
    </div><% end %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/users/_login_form.html.erb
<%= form_for @user, url: login_users_url, html: {class: "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from logging in:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :email, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :email, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :password, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <br>

  <div class="actions text-center">
    <%= link_to welcome_path do %><div class="btn btn-default">
      <span class="glyphicon glyphicon-arrow-left"></span> Back
    </div><% end %>

    <%= f.submit "Log In", class: "btn btn-primary" %>
  </div>

  <br>

  <div class="text-center">
    <p><i>If you have forgotten your password, please contact me via the About page.</i></p>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<% provide :back_path, user_path(@user) %>

<div style="max-width: 50em" class="center-block">
  <%= render 'form' %>
</div>

app/views/users/login.html.erb
<h1>Login</h1>

<div style="max-width: 50em" class="center-block">
  <%= render "login_form" %>
<div>

app/views/users/new.html.erb
<h1>Register</h1>

<% provide :back_path, welcome_path %>

<div style="max-width: 50em" class="center-block">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>

<h3> User Details </h3>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h3> Statistics </h3>

<p>
  <strong>Annotations:</strong>
  <%= @user.annotations.count %>
</p>

<h3> Participant Information </h3>

<ul>
  <li><%= link_to "Information Sheet For Participants", participant_information_path %></li>
</ul>

<br>

<div class="actions">
  <%= link_to projects_path do %><div class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span> Back
  </div><% end %>

  <%= link_to edit_user_path(@user) do %><div class="btn btn-primary">
    <span class="glyphicon glyphicon-pencil"></span> Edit Details
  </div><% end %>
</div>