config/routes.rb
Sage::Application.routes.draw do

  resources :projects do

    resources :digital_objects do
      member do
        post 'add_concept'
        post 'add_created_concept'
        post 'remove_concept'
      end

      collection do
        post 'import_drive_folder'
      end
    end

    resources :concepts do
      member do
        post 'add_object'
        post 'remove_object'
      end
    end

    member do
      get 'statistics'
      get 'import_annotations'
      post 'import_annotations'
      get 'export_annotations'
      post 'export_annotations'
      post 'generate_key'
      post 'reset_key'
      post 'remove_user'
    end

    collection do
      get 'redeem_key'
      post 'check_key'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
    end
  end

  root "site#welcome"

  get "/welcome" => "site#welcome"
  get "/application" => "site#application"
  get "/about" => "site#about"
  get "/participant_information" => "site#participant_information"

  get "/receive_oauth2" => "projects#receive_oauth2"

end

app/controllers/projects_controller.rb
require 'csv'

class ProjectsController < ApplicationController
  before_action :set_project
  before_action :check_access

  layout 'control', except: [:new, :create, :index, :redeem_key, :check_key]

  # GET /receive_oauth2
  def receive_oauth2

    # Get the project id passed in state.
    project_id = params[:state]

    # Check whether the call was successful.
    if params[:error].eql? "access_denied"

      # Unsuccessful. Redirect to project with notice.
      notice = "SAGE was declined access to Google Drive."

    else

      # Get access code.
      code = params[:code]

      # Commence exchange process.
      begin

        # Exchange authorisation code for access token.
        authorisation = GoogleDriveUtils.exchange_code(code)

        # Store authorisation in session.
        session[:access_token] = authorisation.access_token

        # Notify of success.
        notice = "SAGE has been granted temporary access to Google Drive."

      # Rescue from expired code issues.
      rescue CodeExchangeError

        # Notify of error.
        notice = "An issue was encountered while requesting access to Google Drive."
      end
    end

    # Redirect the user.
    redirect_to new_project_digital_object_path(project_id), notice: notice
  end

  # GET /projects/1/import_annotations
  # POST /projects/1/import_annotations
  def import_annotations

    # If receiving data:
    if request.post?

      # Process data.
      begin

        # Call method.
        @project.import_annotations(params[:data], params[:import_method], @user)

        # Redirect back to project path.
        flash.notice = "You have successfully imported the annotations."
        redirect_to project_path(@project)

      rescue CSV::MalformedCSVError

        # Rescue from malformed CSV data.
        flash.alert = "The supplied data was not in valid CSV format."
        redirect_to import_annotations_project_path(@project)

      rescue RuntimeError => e

        # Rescue from error.
        flash.alert = e.message
        redirect_to import_annotations_project_path(@project)
      end
    end
  end

  # GET /projects/1/export_annotations
  # POST /projects/1/export_annotations
  def export_annotations

    # If receiving data:
    if request.post?

      # Fetch the complete array of rows of data to export.
      @data = @project.export_annotations(
        params[:export_mode],
        params[:export_format]
      )
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = @user.projects.order(:name)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @admins = administrator_count

    @administrators = []
    @contributors = []
    @viewers = []

    UserRole.where(project_id: @project.id, position: "Administrator").each do |role|
      @administrators << User.find(role.user_id)
    end

    UserRole.where(project_id: @project.id, position: "Contributor").each do |role|
      @contributors << User.find(role.user_id)
    end

    UserRole.where(project_id: @project.id, position: "Viewer").each do |role|
      @viewers << User.find(role.user_id)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        # Project is initially registered to the creating user.
        UserRole.create user_id: @user.id, project_id: @project.id, position: "Administrator"

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /projects/1/remove_user
  def remove_user

    # Fetch user role.
    role = UserRole.find_by(
      user_id: params[:removed_user_id],
      project_id: @project.id
    )

    # Check for deleting administrators.
    unless role.position.eql? "Administrator"

      # If not administrator, destroy role.
      role.destroy
    end

    # Redirect back to project.
    redirect_to project_path(@project)
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy

    # Remove the user's role from this project.
    @user_role.destroy

    # Check number of admins for deletion method.
    if UserRole.where(project_id: @project.id, position: "Administrator").count == 0

      # Destroy entire project.
      @project.destroy
    end

    # Redirect.
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # GET /projects/redeem_key
  def redeem_key
  end

  # POST /projects/1/generate_key?type=Viewer
  def generate_key

    # Generate a new key for the project.
    @project.generate_key(params[:type])

    # Save project with new details.
    @project.save

    # Redirect back to the project.
    redirect_to @project
  end

  # POST /projects/1/reset_key?type=Viewer
  def reset_key

    # Reset the given key.
    @project.reset_key(params[:type])

    # Save the changes.
    @project.save

    # Redirect back to the project.
    redirect_to @project
  end

  # POST /projects/check_key?key=sdafasddsfsfasfasfdafdaf
  def check_key
    flash.notice = Project.check_key(params[:key], @user)
    redirect_to redeem_key_projects_path
  end

  # GET /projects/1/statistics
  def statistics

    # Get the project's statistics.
    @statistics = Statistics.new(@project.id)
    @object_statistics = @statistics.object_statistics
    @concept_statistics = @statistics.concept_statistics
    @word_statistics = @statistics.word_statistics
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project

      # If the params contains an id:
      if params[:id]

        # Check if the project exists.
        if Project.exists?(params[:id])

          # Set the project.
          @project = Project.find(params[:id])
        else

          # Redirect on error.
          flash[:alert] = "The specified project was not found."
          redirect_to projects_path
        end
      end
    end

    # Set the user role.
    def set_user_role
      @user_role = UserRole.where(user_id: @user.id, project_id: @project.id).first
    end

    # Find how many administrators are in the current project.
    def administrator_count

      # Return the number of administrators.
      return UserRole.where(project_id: @project.id, position:"Administrator").count
    end

    # Check authorisation before access.
    def check_access

      # Check if the user is logged in.
      if !@user
        flash[:notice] = "You are not logged in. Please log in to continue."
        redirect_to login_users_path
        return false
      end

      # Define public (for logged in users) pages.
      public_pages = ["new", "create", "index", "redeem_key", "check_key",
        "receive_oauth2"]

      # Allow user to access public pages.
      if public_pages.include? params[:action]
        return true
      end

      # Get the user's role in this project.
      set_user_role

      # Check user's role.
      if @user_role.nil?

        # User doesn't have a role in this project.
        flash[:notice] = "You don't have access to this project."
        redirect_to projects_path
        return false
      end

      # Define priviledges.
      view = ["show", "destroy", "statistics", "export_annotations"]
      admin = ["update", "edit", "generate_key", "reset_key", "remove_user",
      "import_annotations"]

      # Allocate priviledges to roles.
      priviledges = {
        "Viewer" => view,
        "Annotator" => view,
        "Contributor" => view,
        "Administrator" => view + admin
      }

      # Allow requests with correct permissions.
      if priviledges[@user_role.position].include? params[:action]
        return true
      end

      # Otherwise, no permissions.
      redirect_to "/403.html"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :notes, :algorithm)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  # Determines if a user would be leaving a project, as opposed to deleting.
  def leaving?(user, project)

    # Find how many administrators are in this project.
    admins = UserRole.where(project_id: project.id, position:"Administrator").count

    # Find whether this user is an administrator.
    role = UserRole.where(user_id: user.id, project_id: project.id).first

    # If the user is the last administrator:
    if (admins == 1) && (role.position.eql? "Administrator")

      # User leaving will cause project deletion.
      return false
    else

      # User is free to leave.
      return true
    end
  end

  # Determine algorithm name to present.
  def project_algorithm(algorithm)

    if !algorithm || algorithm.eql?("")

      # No algorithm set.
      return "Default (SAGA)"
    else

      # Return algorithm name.
      return algorithm
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, "Project Name:" %><br>
    <%= f.text_field :name, class: "form-control", autofocus: true %>
  </div>

  <div class="field form-group">
    <%= f.label :notes, "Notes:" %><br>
    <em>Additional information you want to share with other users contributing to this project.</em>
    <%= f.text_area :notes, class: "form-control", rows: 10 %>
  </div>

  <div class="field form-group">
    <%= f.label :algorithm, "Algorithm:" %><br>
    <em>Leave blank to use the default algorithm (SAGA), or choose a specific, enabled algorithm to use in this project.</em>
    <%= f.text_field :algorithm, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= link_to @back_path do %><div class="btn btn-default">
      <span class="glyphicon glyphicon-arrow-left"></span> Back
    </div><% end %>

    <%= f.submit "Done", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_key.html.erb
<div class="row" style= "margin: 10px">

  <div class="col-md-3"><strong><%= position %> Key:</strong></div>

  <div class="col-md-5 text-center"> <%= key %> </div>

  <div class="col-md-4">
    <%= link_to generate_key_project_path(@project, type: position), method: :post do %>
      <div class="btn btn-default">
        <i class="glyphicon glyphicon-certificate"></i> Generate
      </div><% end %>
    <%= link_to reset_key_project_path(@project, type: position), method: :post do %>
      <div class="btn btn-default">
        <i class="glyphicon glyphicon-erase"></i> Remove
      </div><% end %>
  </div>

</div>

app/views/projects/analytics.html.erb
<h1>Analytics: <%= @project.name %></h1>

<table class="table table-bordered">
  <tr>
    <th class="text-center">Item</th>
    <th class="text-center">Count</th>
  </tr>
  <tr>
    <td colspan="2"> <strong>Counts</strong> </td>
  <tr>
  <tr>
    <td>Number of Users</td>
    <td><%= @statistics[:user_count] || 0 %> </td>
  </tr>
  <tr>
    <td>Number of Objects</td>
    <td><%= @statistics[:objects_count] || 0 %> </td>
  </tr>
  <tr>
    <td>Number of Concepts</td>
    <td><%= @statistics[:concepts_count] || 0 %> </td>
  </tr>
  <tr>
    <td>Number of Annotations</td>
    <td><%= @statistics[:annotations_count] || 0 %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Objects</strong> </td>
  <tr>
  <tr>
    <td>Objects - Minimum Annotations</td>
    <td><%= @statistics[:min_objects] || 0 %> </td>
  </tr>
  <tr>
    <td>Objects - Average Annotations</td>
    <td><%= @statistics[:avg_objects].round(2) || 0 %> </td>
  </tr>
  <tr>
    <td>Objects - Maximum Annotations</td>
    <td><%= @statistics[:max_objects] || 0 %> </td>
  </tr>
  <tr>
    <td>Objects - Standard Deviation</td>
    <td><%= @statistics[:object_std_deviation].round(2) %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Concepts</strong> </td>
  <tr>
  <tr>
    <td>Concepts - Minimum Annotations</td>
    <td><%= @statistics[:min_concepts] || 0 %> </td>
  </tr>
  <tr>
    <td>Concepts - Average Annotations</td>
    <td><%= @statistics[:avg_concepts].round(2) || 0 %> </td>
  </tr>
  <tr>
    <td>Concepts - Maximum Annotations</td>
    <td><%= @statistics[:max_concepts] || 0 %> </td>
  </tr>
  <tr>
    <td>Concepts - Standard Deviation</td>
    <td><%= @statistics[:concept_std_deviation].round(2) %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Words</strong> </td>
  <tr>
  <tr>
    <td>Words - Minimum Concept Word Count</td>
    <td><%= @statistics[:min_words] || 0 %> </td>
  </tr>
  <tr>
    <td>Words - Average Concept Word Count</td>
    <td><%= @statistics[:avg_words].round(2) || 0 %> </td>
  </tr>
  <tr>
    <td>Words - Maximum Concept Word Count</td>
    <td><%= @statistics[:max_words] || 0 %> </td>
  </tr>
  <tr>
    <td>Words - Total Concept Word Count</td>
    <td><%= @statistics[:word_count] || 0 %> </td>
  </tr>
</table>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<% @back_path = project_path(@project) %>
<%= render 'form' %>

app/views/projects/export_annotations.csv.erb
<% @data.each do |line| %><%= CSV.generate_line(line, force_quotes: :true).html_safe %><% end %>

app/views/projects/export_annotations.html.erb
<h1> Export Annotations </h1>

<em> This feature allows you to export the information contained in this SAGE
  project. The data will be made available in a CSV file, which can be opened
  by any spreadsheet application. Exported projects can be re-imported in
  another SAGE project to create copies and share data.</em>

<%= form_tag export_annotations_project_path(@project, format: :csv) do %>

  <h3> Data </h3>
  <em>Select the data to export from this project.</em>

  <div class="radio">
    <label>
      <%= radio_button_tag "export_mode", "complete", class:"active" %>
      Complete: All objects, concepts, and their annotations.
    </label>
  </div>

  <div class="radio">
    <label>
      <%= radio_button_tag "export_mode", "objects" %>
      All Objects: All objects and their annotations. Excludes concepts that aren't used in annotations.
    </label>
  </div>

  <div class="radio">
    <label>
      <%= radio_button_tag "export_mode", "annotations" %>
      Annotated Objects: Only annotated objects and their annotations. Excludes objects and concepts that aren't annotated.
    </label>
  </div>

  <h3> Format </h3>
  <em>Select how objects are represented in the exported file.</em>

  <div class="radio">
    <label>
      <%= radio_button_tag "export_format", "url", class: "active" %>
      URL: Export the complete URL of objects in the project. Recommended for web applications.
    </label>
  </div>

  <div class="radio">
    <label>
      <%= radio_button_tag "export_format", "filename" %>
      Filename: Export the filename of objects in the project. Recommended for desktop applications.
    </label>
  </div>

  <%= link_to project_path(@project) do %><div class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span> Back
  </div><% end %>

  <%= submit_tag "Export", class: "btn btn-primary" %>

<% end %>

app/views/projects/import_annotations.html.erb
<h1> Import Annotations </h1>

<%= form_tag import_annotations_project_path(@project) do %>

  <h3> CSV Data </h3>
  <%= text_area_tag "data", nil, rows: 15, class: "form-control" %>

  <h3> Import Type </h3>

  <div class="radio">
    <label>
      <%= radio_button_tag "import_method", "complete", class:"active" %>
      Complete Import: Matches objects using URLs or plain text. Adds to existing objects when found, or creates new objects.
    </label>
  </div>

  <div class="radio">
    <label>
      <%= radio_button_tag "import_method", "selective" %>
      Selective Import: Matches objects using URLs or plain text. Adds only to existing objects.
    </label>
  </div>

  <div class="radio">
    <label>
      <%= radio_button_tag "import_method", "filename" %>
      Filename Import: Matches objects using their filename. Adds only to existing objects.
    </label>
  </div>

  <p><i>
    * Note that filename imports are likely to be somewhat unpredictable unless
    the original objects that have been added to the project have been named in
    such a way as to avoid duplicate filenames.
  </i></p>

  <%= link_to project_path(@project) do %><div class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span> Back
  </div><% end %>

  <%= submit_tag "Import", class: "btn btn-primary" %>

<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class="row">
  <div class="col-md-6">
    <%= link_to "New Project", new_project_path, class: "btn btn-default btn-lg btn-block" %>
  </div>
  <div class="col-md-6">
    <%= link_to "Redeem Key", redeem_key_projects_path, class: "btn btn-default btn-lg btn-block" %>
  </div>
</div>

<br>

<table class="table table-striped table-bordered">
  <% @projects.each do |project| %>
    <tr>
    	<td class="nodecoration">
        <%= link_to project_path(project), title: "View" do %>
          <%= truncate(project.name, length: 100) %>
        <% end %>
    	  <div class="pull-right">
          <% if leaving? @user, project %>
            <%= link_to project_path(project), title: "Leave", method: :delete,
              data: { confirm: 'Are you sure you wish to leave this project?' } do %>
              <i class="glyphicon glyphicon-off"></i>
            <% end %>
          <% else %>
            <%= link_to project_path(project), title: "Delete", method: :delete,
              data: { confirm: 'Are you sure you wish to delete this project?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<% @back_path = projects_path %>
<%= render 'form' %>

app/views/projects/redeem_key.html.erb
<h1>Redeem Key</h1>
<%= form_tag (check_key_projects_path) do %>

  <div class="field form-group">
    <%= label_tag :key, 'Key:'%><br>
    <%= text_field_tag :key, "", class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= link_to projects_path do %><div class="btn btn-default">
      <span class="glyphicon glyphicon-arrow-left"></span> Back
    </div><% end %>

    <%= submit_tag "Done", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/show.html.erb
<h1 class="text-center"><%= @project.name %></h1>
<h4 class="text-center">Algorithm: <%= project_algorithm @project.algorithm %></h4>

<div class="well" style="white-space: pre-wrap"><%= @project.notes %></div>

<% if @user_role.position.eql? "Administrator" %>

  <div class="row">
    <div class="col-md-12 text-center">
    <%= link_to projects_path do%>
      <div class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Back
    </div><% end %>
    <%= link_to edit_project_path(@project), title: "Edit" do %>
      <div class="btn btn-default"><i class="glyphicon glyphicon-pencil"></i> Edit
    </div><% end %>
    <%= link_to import_annotations_project_path(@project) do%>
      <div class="btn btn-default"><i class="glyphicon glyphicon-import"></i> Import Annotations
    </div><% end %>
    <%= link_to export_annotations_project_path(@project) do%>
      <div class="btn btn-default"><i class="glyphicon glyphicon-export"></i> Export Annotations
    </div><% end %>
    <% if @admins > 1 %>
      <%= link_to project_path(@project), title: "Leave", method: :delete,
        data: {confirm: 'Are you sure you wish to leave this project?'} do %>
        <div class="btn btn-default"><i class="glyphicon glyphicon-off"></i> Leave
      </div><% end %>
    <% else %>
      <%= link_to project_path(@project), title: "Delete", method: :delete,
        data: { confirm: 'Are you sure you wish to delete this project?' } do %>
        <div class="btn btn-default"><i class="glyphicon glyphicon-trash"></i> Delete
      </div><% end %>
    <% end %>
    </div>
  </div>

  <br>

  <%= render partial: "key",
    locals: { position: "Administrator", key: @project.administrator_key }
  %>

  <%= render partial: "key",
    locals: { position: "Contributor", key: @project.contributor_key }
  %>

  <%= render partial: "key",
    locals: { position: "Annotator", key: @project.annotator_key }
  %>

  <%= render partial: "key",
    locals: { position: "Viewer", key: @project.viewer_key }
  %>

<% else %>

  <div class="row">
    <div class="col-md-3"></div>

    <%= link_to projects_path do%>
      <div class="col-md-2 btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Back</div>
    <% end %>

    <div class="col-md-2"></div>
    <%= link_to project_path(@project), title: "Leave", method: :delete,
      data: {confirm: "Are you sure you wish to leave this project?"} do %>
      <div class="col-md-2 btn btn-default"><i class="glyphicon glyphicon-off"></i> Leave</div>
    <% end %>

    <div class="col-md-3"></div>
  </div>

<% end %>

<br>

<% if @administrators.count > 0 %>
<div>
  <strong>Administrators:</strong><br>
  <% @administrators.each do |user| %>
    <p style="margin-left:2em"><%= user.name %> (<%= user.email %>)</p>
  <% end %>
</div>
<% end %>

<% if @user_role.position.eql? "Administrator" %>

  <% if @contributors.count > 0 %>
  <div>
    <strong>Contributors:</strong><br>
    <% @contributors.each do |user| %>
      <div>
        <%= link_to remove_user_project_path(@project, removed_user_id: user.id), method: :post do %><div class="btn btn-default">
          <span class="glyphicon glyphicon-remove-circle"></span> Remove
        </div><% end %>
        <span style="margin-left:2em"><%= user.name %> (<%= user.email %>)</span>
      </div>
    <% end %>
  </div>
  <% end %>

  <% if @viewers.count > 0 %>
  <div>
    <strong>Viewers:</strong><br>
    <% @viewers.each do |user| %>
      <div>
        <%= link_to remove_user_project_path(@project, removed_user_id: user.id), method: :post do %><div class="btn btn-default">
          <span class="glyphicon glyphicon-remove-circle"></span> Remove
        </div><% end %>
        <span style="margin-left:2em"><%= user.name %> (<%= user.email %>)</span>
      </div>
    <% end %>
  </div>
  <% end %>

<% end %>

app/views/projects/statistics.html.erb
<h1>Statistics: <%= @project.name %></h1>

<table class="table table-bordered">
  <tr>
    <th class="text-center">Item</th>
    <th class="text-center">Count</th>
  </tr>
  <tr>
    <td colspan="2"> <strong>Counts</strong> </td>
  <tr>
  <tr>
    <td>Number of Users</td>
    <td><%= @statistics.user_count %> </td>
  </tr>
  <tr>
    <td>Number of Objects</td>
    <td><%= @statistics.object_count %> </td>
  </tr>
  <tr>
    <td>Number of Concepts</td>
    <td><%= @statistics.concept_count %> </td>
  </tr>
  <tr>
    <td>Number of Annotations</td>
    <td><%= @statistics.annotation_count %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Objects</strong> </td>
  <tr>
  <tr>
    <td>Objects - Minimum Annotations</td>
    <td><%= @object_statistics.min %> </td>
  </tr>
  <tr>
    <td>Objects - Average Annotations</td>
    <td><%= @object_statistics.mean %> </td>
  </tr>
  <tr>
    <td>Objects - Maximum Annotations</td>
    <td><%= @object_statistics.max %> </td>
  </tr>
  <tr>
    <td>Objects - Standard Deviation</td>
    <td><%= @object_statistics.std_dev %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Concepts</strong> </td>
  <tr>
  <tr>
    <td>Concepts - Minimum Annotations</td>
    <td><%= @concept_statistics.min %> </td>
  </tr>
  <tr>
    <td>Concepts - Average Annotations</td>
    <td><%= @concept_statistics.mean %> </td>
  </tr>
  <tr>
    <td>Concepts - Maximum Annotations</td>
    <td><%= @concept_statistics.max %> </td>
  </tr>
  <tr>
    <td>Concepts - Standard Deviation</td>
    <td><%= @concept_statistics.std_dev %> </td>
  </tr>
  <tr>
    <td colspan="2"> <strong>Words</strong> </td>
  <tr>
  <tr>
    <td>Words - Minimum Concept Word Count</td>
    <td><%= @word_statistics.min %> </td>
  </tr>
  <tr>
    <td>Words - Average Concept Word Count</td>
    <td><%= @word_statistics.mean %> </td>
  </tr>
  <tr>
    <td>Words - Maximum Concept Word Count</td>
    <td><%= @word_statistics.max %> </td>
  </tr>
  <tr>
    <td>Words - Total Concept Word Count</td>
    <td><%= @word_statistics.std_dev %> </td>
  </tr>
</table>