config/routes.rb
Sage::Application.routes.draw do

  resources :projects do

    resources :digital_objects do
      member do
        post 'add_concept'
        post 'add_created_concept'
        post 'remove_concept'
      end

      collection do
        post 'import_drive_folder'
      end
    end

    resources :concepts do
      member do
        post 'add_object'
        post 'remove_object'
      end
    end

    member do
      get 'statistics'
      get 'import_annotations'
      post 'import_annotations'
      get 'export_annotations'
      post 'export_annotations'
      post 'generate_key'
      post 'reset_key'
      post 'remove_user'
    end

    collection do
      get 'redeem_key'
      post 'check_key'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
    end
  end

  root "site#welcome"

  get "/welcome" => "site#welcome"
  get "/application" => "site#application"
  get "/about" => "site#about"
  get "/participant_information" => "site#participant_information"

  get "/receive_oauth2" => "projects#receive_oauth2"

end

app/models/digital_object.rb
class DigitalObject < ActiveRecord::Base

  has_many :annotations, dependent: :destroy
  has_many :concepts, through: :annotations
  belongs_to :project

  validates :location, presence: true

  before_save :update_details, if: :location_changed?
  after_create :create_thumbnails

  # Map algorithms to names.
  ALGORITHMS = {
    '' => SAGA::Object,
    'SAGA' => SAGA::Object,
    'SAGA-Refined' => SAGA::Object_Refined,
    'Shuffle' => Shuffle::Object,
    'Annotated' => Annotated::Object,
    'None' => None::Object,
    'All' => All::Object,
    'Vote' => TagRecommendationStrategies::Vote,
    'VotePlus' => TagRecommendationStrategies::VotePlus,
    'Sum' => TagRecommendationStrategies::Sum,
    'SumPlus' => TagRecommendationStrategies::SumPlus
  }

  # Find entities by annotation.
  def related

    # Return the entities associated with this element.
    return concepts.to_a
  end

  # Wrap self in an algorithm.
  def algorithm(specific = nil)

    # Get algorithm name. Check specific for overrides, then project.
    name = specific || project.algorithm

    # If a valid algorithm name wasn't provided, use default.
    if !ALGORITHMS.key? name
      name = ""
    end

    # Return object.
    return ALGORITHMS[name].new(self)
  end

  # Check if valid algorithm has been provided.
  def valid_algorithm?(algorithm = project.algorithm)

    # True if blank or registered algorithm.
    return (!algorithm || (ALGORITHMS.key? algorithm))
  end

  # Get a thumbnail for the specified size and object.
  def thumbnail(x, y)

    # If the thumbnail hasn't been set for this object:
    if thumbnail_url.nil?

      # Generate thumbnail url.
      generate_thumbnail_url
    end

    # Retrieve a thumbnail for this object.
    Thumbnail.find_for(thumbnail_url, x, y)
  end

  # Check if the object's location is likely to be a link.
  def has_uri?

    # Compare location with a valid URI's regexp.
    return location =~ %r{\A#{URI::regexp}\z}
  end

  # Update the object's details when changing locations.
  def update_details

    # Check new location for needed conversions.
    check_conversions

    # Check for flattening.
    check_flatten

    # Update filename.
    set_filename

    # Update thumbnail.
    reset_thumbnail_url

    # Indicate save can continue.
    return true
  end

  # Private methods.
  private

  # Checks if a given location should be changed before saving, particularly
  # when using other services as content providers.
  def check_conversions

    # Define locations with ID captures.
    google_drive = %r{\Ahttps://drive.google.com/open\?id=(?<file_id>\w+)\z}
    google_apis = %r{\Ahttps://www.googleapis.com/drive/v2/files/(?<file_id>\w+)\z}

    # Check Google Drive locations.
    if (data = google_drive.match location)
      self.location = "https://docs.google.com/uc?id=#{data[:file_id]}"
    end

    # Check Google APIs locations.
    if (data = google_apis.match location)
      self.location = "https://docs.google.com/uc?id=#{data[:file_id]}"
    end
  end

  # Check if two or more objects shall be flattened:
  def check_flatten

    # Find all digital objects with the same project id and location.
    same_objects = DigitalObject.where(
      project_id: project_id,
      location: location
    ).to_a

    # Remove self.
    same_objects.delete(self)

    # If other objects have the same attributes:
    if same_objects.count > 0

      # For each object:
      same_objects.each do |same_object|

        # Flatten that object into this object.
        flatten(same_object)
      end
    end
  end

  # Set the filename for the object.
  def set_filename

    # If the source is not a URI:
    if location !~ %r{\A#{URI::regexp}\z}

      # Filename should be text.
      self.filename = location

    # The source is a URI.
    else

      # Attempt to fetch resource data.
      begin

        # Check if Google resource.
        if location =~ GoogleDriveUtils::GOOGLE_DOCS_REGEXP

          # Define regular expression.
          google_docs = %r{\Ahttps://docs.google.com/uc\?id=(?<file_id>\w+)\z}

          # Capture filename.
          data = google_docs.match location

          # Form APIs URL.
          apis_location = "https://www.googleapis.com/drive/v2/files/#{data[:file_id]}"

          # Fetch resource's information using key.
          information = RestClient.get(
            apis_location, { params: { key: ENV["GOOGLE_API_KEY"] } }
          )

          # Update filename based on resource information.
          self.filename = JSON.parse(information)["title"]

        # Otherwise, does not need an access key.
        else

          # Update filename based on resource information.
          self.filename = File.basename(location)
        end

      # Rescue in the event of an error.
      rescue RestClient::Exception

        # Use a missing filename.
        self.filename = "Missing"
      end
    end
  end

  # Resets the thumbnail url every time the location changes.
  def reset_thumbnail_url

    # Set thumbnail url to nil.
    self.thumbnail_url = nil

    # Allow save to continue.
    return true
  end

  # Generates this object's thumbnail URL.
  def generate_thumbnail_url

    # Initialise to default.
    self.thumbnail_url = location

    # Define locations with ID captures.
    wcl_location = %r{\Ahttps://docs.google.com/uc\?id=(?<file_id>\w+)\z}

    # Check Google locations.
    if (data = wcl_location.match location)
      self.thumbnail_url = "https://www.googleapis.com/drive/v2/files/#{data[:file_id]}"
    end

    # Commit changes.
    self.save
  end

  # Schedule for common thumbnail sizes to be created.
  def create_thumbnails

    # Create the common thumbnail sizes.
    Thumbnail::COMMON_SIZES.each do |size|
      thumbnail(size,size)
    end
  end

  # Flatten another digital object into this one.
  def flatten(other_object)

    # Go through the other object's annotations.
    Annotation.where(digital_object: other_object).each do |prospective|

      # Check if already annotated.
      unless concepts.include? prospective.concept

        # Modify annotation.
        prospective.update(digital_object_id: id)
      end
    end

    # Accept other object's thumbnail base (e.g. if a custom thumbnail base).
    thumbnail_url = other_object.thumbnail_url

    # Destroy the flattened object.
    other_object.destroy
  end
end

app/controllers/digital_objects_controller.rb
class DigitalObjectsController < ApplicationController
  before_action :set_project
  before_action :set_digital_object
  before_action :check_access

  layout 'control'

  helper ThumbnailHelper

  # Four images per row, seven rows.
  DEFAULT_PAGE_ITEMS = 28

  # GET /digital_objects
  # GET /digital_objects.json
  def index

    # Find the current page.
    page = current_page
    start_index = page * page_items
    end_index = start_index + page_items

    # Initialise previous and next pages.
    @previous_page = nil
    @next_page = nil

    # Determine if a previous page is possible.
    if page > 0
      @previous_page = page - 1
    end

    # Determine if a next page is possible.
    if end_index < @project.digital_objects.count
      @next_page = page + 1
    end

    # Retrieve a page of results or an empty array if none.
    @digital_objects = @project.object_index[start_index...end_index] || []
  end

  # GET /digital_objects/1
  # GET /digital_objects/1.json
  def show

    # New concept for quick create.
    @concept = Concept.new

    # Get object listing.
    items = @project.object_index

    # Get index of this object within listing.
    index = items.find_index(@digital_object)

    # Determine relative links.
    @index_page = index / page_items
    @random_item = items[Random.rand(items.count)].id
    @previous_item = nil
    @next_item = nil

    # Find previous item.
    if index > 0
      @previous_item = items[index - 1].id
    end

    # Find next item.
    if index < (items.count - 1)
      @next_item = items[index + 1].id
    end

    # Check valid algorithm.
    if !@digital_object.valid_algorithm?
      flash.now[:notice] = "The project's algorithm (#{@project.algorithm})"\
        " doesn't support objects. Using the default algorithm instead."
    end
  end

  # GET /digital_objects/new
  def new
    @digital_object = DigitalObject.new
    @have_google_authorisation = session[:access_token]
    # @google_authorisation_uri = GoogleDriveUtils.get_authorization_url(@project.id)
  end

  # GET /digital_objects/1/edit
  def edit
  end

  # POST /digital_objects
  # POST /digital_objects.json
  def create

    # Get location list.
    locations = digital_object_params[:location].lines

    # Flag to test whether new object could be saved.
    saved = true;

    # Modify params for each location, and use them to create objects.
    locations.each do |location|

      # Create digital object.
      saved &= DigitalObject.find_or_create_by(
        project_id: @project.id,
        location: location.chomp
      )
    end

    # Set notice.
    if locations.count > 1 && saved
      notice = "Digital objects were successfully created."
    elsif saved
      notice = "Digital object was successfully created."
    end

    respond_to do |format|
      if saved
        format.html { redirect_to project_digital_objects_path, notice: notice }
        format.json { render action: 'index', status: :created, location: @digital_object }
      else
        format.html { render action: 'new' }
        format.json { render json: @digital_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /digital_objects/1
  # PATCH/PUT /digital_objects/1.json
  def update
    respond_to do |format|
      if @digital_object.update(digital_object_params)
        format.html { redirect_to [@project, @digital_object], notice: 'Digital object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @digital_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /digital_objects/1
  # DELETE /digital_objects/1.json
  def destroy
    @digital_object.destroy
    respond_to do |format|
      format.html { redirect_to project_digital_objects_url }
      format.json { head :no_content }
    end
  end

  # POST /objects/1/add_concept
  def add_concept
    set_concept

    unless @digital_object.concepts.include? @concept
      Annotation.create(
        digital_object_id: @digital_object.id,
        concept_id: @concept.id,
        user_id: session[:user_id],
        provenance: "Existing"
      )
    end

    respond_to do |format|
      format.html { redirect_to project_digital_object_path(@project, @digital_object) }
      format.js { render 'annotations.js.erb' }
    end
  end

  # POST /objects/1/add_created_concept
  def add_created_concept

    # Details.
    details = params.require(:concept).permit(:description)
    details[:project_id] = @project.id

    # Create new concept.
    @concept = Concept.match_or_create(details)

    # Attempt to save.
    if @concept

      # Associate new concept with this object.
      unless @digital_object.concepts.include? @concept
        Annotation.create(
          digital_object_id: @digital_object.id,
          concept_id: @concept.id,
          user_id: session[:user_id],
          provenance: "New"
        )
      end

      # Redirect with success.
      redirect_to project_digital_object_path(@project, @digital_object)
    else

      # Redirect with failure.
      redirect_to project_digital_object_path(@project, @digital_object),
        notice: 'Concept was not able to be created.'
    end
  end

  # POST /objects/1/remove_object
  def remove_concept
    set_concept

    if @digital_object.concepts.include? @concept
      @digital_object.concepts.destroy @concept
    end

    respond_to do |format|
      format.html { redirect_to project_digital_object_path(@project, @digital_object) }
      format.js { render 'annotations.js.erb' }
    end
  end

  # POST /objects/1/import_drive_folder
  def import_drive_folder

    # Get the specified folder.
    folder = params[:drive_folder]

    begin

      # Import folder.
      notice = GoogleDriveUtils.import_drive_folder(
        folder,
        @project.id,
        session[:access_token]
      )

    rescue ExpiredAuthError

      # Set notice and expire access_token.
      notice = "Your authorisation of SAGE to access Google Drive has " +
        "expired. Please renew authorisation to continue."
      session[:access_token].delete
    end

    # Redirect to object listing.
    redirect_to project_digital_objects_path(@project),
      notice: notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_digital_object

      # If params contains an id:
      if params[:id]

        # Check if the object exists.
        if DigitalObject.exists?(params[:id])

          # Set the digital object.
          @digital_object = DigitalObject.find(params[:id])
        else

          # Redirect on error.
          flash[:alert] = "The specified object was not found."
          redirect_to project_digital_objects_path(@project)
        end
      end
    end

    def set_concept
      @concept = Concept.find(params[:concept_id])
    end

    def set_project

      # Check if the project exists.
      if Project.exists?(params[:project_id])

        # Set the project.
        @project = Project.find(params[:project_id])
      else

        # Redirect on error.
        flash[:alert] = "The specified project was not found."
        redirect_to projects_path
      end
    end

    # Get the role of the user in this project.
    def set_user_role
      @user_role = UserRole.find_by(user_id: session[:user_id], project_id: params[:project_id])
    end

    # Find the number of page items.
    def page_items

      # Check if the user is a viewer.
      if @user_role.position.eql? "Viewer"
        return DEFAULT_PAGE_ITEMS
      else

        # Leave room for create button.
        return DEFAULT_PAGE_ITEMS - 1
      end
    end

    # Check authorisation before access.
    def check_access

      # Check if the user is logged in.
      if !@user
        flash[:notice] = "You are not logged in. Please log in to continue."
        redirect_to login_users_path
        return false
      end

      # Get the user's role in this project.
      set_user_role

      # Check user's role.
      if @user_role.nil?

        # User doesn't have a role in this project.
        flash[:notice] = "You don't have access to this project."
        redirect_to projects_path
        return false
      end

      # Define priviledges.
      view = ["show", "index"]
      annotate = ["add_concept", "remove_concept", "add_created_concept"]
      edit = ["new", "create", "update", "edit", "destroy",
        "import_drive_folder"]

      # Allocate priviledges to roles.
      priviledges = {
        "Viewer" => view,
        "Annotator" => view + annotate,
        "Contributor" => view + annotate + edit,
        "Administrator" => view + annotate + edit
      }

      # Allow requests with correct permissions.
      if priviledges[@user_role.position].include? params[:action]
        return true
      end

      # Otherwise, no permissions.
      redirect_to "/403.html"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def digital_object_params
      params.require(:digital_object).permit(:location)
    end

    # Find the index of the first object in this page.
    def current_page

      # Clean and retrieve page param.
      /(?<page>\d+)/ =~ params[:page]

      # Check for no page.
      if !page

        # Default to zero.
        page = 0
      end

      # Return page.
      return page.to_i
    end
end

app/helpers/digital_objects_helper.rb
module DigitalObjectsHelper
end

app/views/digital_objects/_form.html.erb
<%= form_for([@project, @digital_object]) do |f| %>

  <% if @digital_object.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@digital_object.errors.count, "error") %> prohibited this digital_object from being saved:</h2>

      <ul>
      <% @digital_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :location, "Object URL:" %><br>

    <% if @digital_object.new_record? %>
      <em>Enter the object's URL, or enter multiple URLs on separate lines.</em>
      <%= f.text_area :location, class: "form-control", rows: 10, autofocus: true %>
    <% else %>
      <em>Update the object's URL.</em>
      <%= f.text_field :location, class: "form-control", autofocus: true %>
    <% end %>
  </div>

  <div class="actions form-group">
    <%= link_to project_digital_objects_path(@project) do %><div class="btn btn-default">
      <span class="glyphicon glyphicon-arrow-left"></span> Back
    </div><% end %>

    <%= f.submit "Done", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/digital_objects/_object.html.erb
<div class="nodecoration text-center">

  <%= link_to project_digital_object_path(id: object.id) do%>

    <% if gallery %>
      <div style="height: <%= size %>">
    <% else %>
      <div>
    <% end %>
      <% thumbnail = object.thumbnail(size, size) %>
      <%= image_tag thumbnail_url(thumbnail),
        id: "thumbnail_#{object.id}",
        class: thumbnail_class(thumbnail, gallery) + " rounded",
        style: thumbnail_style(thumbnail)
      %>
    </div>

    <div class="truncate">
      <%= object.filename || "Processing..." %>
    </div>
  <% end %>

  <% if controls && (!@user_role.position.eql? "Viewer") %>
    <%= link_to "#", title: "Flip Image", onclick: "$('#thumbnail_#{object.id}').toggleClass('flipped')" do %>
      <i class="glyphicon glyphicon-resize-horizontal">
    </i><% end %>

    <% if object.has_uri? %>
      <%= link_to object.location, title: "Link", target: "_blank" do %>
        <i class="glyphicon glyphicon-link">
      </i><% end %>
    <% end %>

    <%= link_to edit_project_digital_object_path(id: object.id), title: "Edit" do %>
      <i class="glyphicon glyphicon-pencil">
    </i><% end %>

    <%= link_to project_digital_object_path(id: object.id), title: "Delete", method: :delete, data: { confirm: 'Are you sure you wish to delete this object?' } do %>
      <i class="glyphicon glyphicon-trash">
    </i><% end %>
  <% end %>

</div>

app/views/digital_objects/_objectcontrols.html.erb
<div class="col-sm-3 col-xs-6" style="height: 240px">

  <%= render partial: "digital_objects/object",
    locals: {
      object: object,
      size: '150px',
      controls: false,
      gallery: true
    }
  %>

  <% if !@user_role.position.eql? "Viewer" %>
    <div class="text-center">
      <% if @concept.digital_objects.include? object %>
        <%= link_to remove_object_project_concept_path(@project, @concept, object_id: object.id), method: :post, remote: true, title: "Remove" do %>
          <div class="btn btn-primary">
            <%= score.round(2) %> <i class="glyphicon glyphicon-ok"></i>
          </div>
        <% end %>
      <% else %>
        <%= link_to add_object_project_concept_path(@project, @concept, object_id: object.id), method: :post, remote: true, title: "Add" do %>
          <div class="btn btn-default">
            <%= score.round(2) %> <i class="glyphicon glyphicon-ok fade"></i>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/digital_objects/_tabform.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#url" role="tab" data-toggle="tab">
    Add URLs <span class="glyphicon glyphicon-globe"></span>
  </a></li>
  <li role="presentation"><a href="#drive" role="tab" data-toggle="tab">
    Google Drive Import <%= image_tag "drive_icon.png", size: "16" %>
  </a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="url">

    <%= render 'form' %>

  </div>

  <div role="tabpanel" class="tab-pane" id="drive">

    <% if @have_google_authorisation %>

      <%= form_tag "/projects/#{@project.id}/digital_objects/import_drive_folder",
        class: "form" do %>
        <div class="form-group">
          <label for="drive_folder"> Google Drive folder's link: </label>
          <%= text_field_tag "drive_folder", nil, class: "form-control" %>
        </div>
        <%= submit_tag "Done", class: "btn btn-primary" %>
        <em style="margin-left: 2em"> Note that this may take a while (20 seconds or so) for very large folders. </em>
      <% end %>

    <% else %>

      <p>
        In order to import a public folder, you need to grant SAGE permission
        to access your Google Drive™ account. This permission will last until
        you log out of your SAGE account. You can grant permission using the
        button below.
      </p>
      <br>
      <div class="text-center">
        <%= link_to @google_authorisation_uri do %>
          <div class="btn btn-primary">Authorise SAGE</div>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/digital_objects/annotations.js.erb
$('#annotations').empty();

$('#annotations').append(" <%= escape_javascript(
    render partial: 'concepts/concepttable',
      locals: {
        digital_object: @digital_object,
        project: @project,
      }
) %> ");

app/views/digital_objects/edit.html.erb
<h1>Edit Object</h1>

<%= render 'form' %>

app/views/digital_objects/index.html.erb
<h1>Objects</h1>

<% if !@user_role.position.eql? "Viewer" %>
  <div class="col-sm-3 col-xs-6 text-center" style="height: 220px">
    <%= link_to new_project_digital_object_path, title: "Create" do %>
      <div class="btn btn-default" style="height: 150px; width: 150px">
        <%= image_tag asset_path("add_file.png"), style: "height: 100%; width: auto;" %>
      </div>
    <% end %>
  </div>
<% end %>

<% @digital_objects.each do |digital_object| %>
  <div class="col-sm-3 col-xs-6" style="height: 220px">
    <%= render partial: "object",
      locals: {
        object: digital_object,
        size: '150px',
        controls: true,
        gallery: true
      }
    %>
  </div>
<% end %>

<div class="col-xs-12 text-center">

  <% if @previous_page %>
    <%= link_to project_digital_objects_path(page: @previous_page), title: "Previous" do %>
      <div class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Previous
    </div><% end %>
  <% end %>

  <% if @next_page %>
    <%= link_to project_digital_objects_path(page: @next_page), title: "Next" do %>
      <div class="btn btn-default"><span class="glyphicon glyphicon-arrow-right"></span> Next
    </div><% end %>
  <% end %>

</div>

app/views/digital_objects/new.html.erb
<h1>New Object</h1>

<%= render 'tabform' %>

app/views/digital_objects/show.html.erb
<div class="row nodecoration">
  <div class="col-md-6">
    <div class="text-center well">
      <%= render partial: "object",
        locals: {
          object: @digital_object,
          size: '400px',
          controls: true,
          gallery: false
        }
      %>
    </div>

    <div class="text-center">
      <%= link_to project_digital_objects_path(page: @index_page), title: "Back to Index" do %>
        <div class="btn btn-default"><span class="glyphicon glyphicon-step-backward"></span> Back
      </div><% end %>

      <% if @previous_item %>
        <%= link_to project_digital_object_path(id: @previous_item), title: "Previous" do %>
          <div class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Previous
        </div><% end %>
      <% end %>

      <% if @next_item %>
        <%= link_to project_digital_object_path(id: @next_item), title: "Next" do %>
          <div class="btn btn-default"><span class="glyphicon glyphicon-arrow-right"></span> Next
        </div><% end %>
      <% end %>

      <%= link_to project_digital_object_path(id: @random_item), title: "Random" do %>
        <div class="btn btn-default"><span class="glyphicon glyphicon-step-forward"></span> Random
      </div><% end %>
    </div>
  </div>

  <div class="col-md-6">
    <h1>Concept Annotations</h1>

    <% if !@user_role.position.eql? "Viewer" %>
      <%= form_for @concept, url: {action: "add_created_concept"}, html: {class: "form-inline"} do |f| %>
        <div class="input-group", style="width: 100%">
          <%= f.text_field :description, class: "form-control", autofocus: true %>
          <span class="input-group-btn">
            <%= f.submit "Add", class: "btn btn-primary", style: "width: 100%" %>
          </span>
        </div>
      <% end %>
    <% end %>

    <br>

    <div id="annotations">
      <%= render partial: "concepts/concepttable",
        locals: {
          digital_object: @digital_object,
          project: @project,
        }
      %>
    </div>

  </div>
</div>