config/routes.rb
Sage::Application.routes.draw do

  resources :projects do

    resources :digital_objects do
      member do
        post 'add_concept'
        post 'add_created_concept'
        post 'remove_concept'
      end

      collection do
        post 'import_drive_folder'
      end
    end

    resources :concepts do
      member do
        post 'add_object'
        post 'remove_object'
      end
    end

    member do
      get 'statistics'
      get 'import_annotations'
      post 'import_annotations'
      get 'export_annotations'
      post 'export_annotations'
      post 'generate_key'
      post 'reset_key'
      post 'remove_user'
    end

    collection do
      get 'redeem_key'
      post 'check_key'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'login'
      get 'logout'
    end
  end

  root "site#welcome"

  get "/welcome" => "site#welcome"
  get "/application" => "site#application"
  get "/about" => "site#about"
  get "/participant_information" => "site#participant_information"

  get "/receive_oauth2" => "projects#receive_oauth2"

end

app/views/layouts/_header.html.erb
<nav class="navbar-wrapper navbar-inverse" role="navigation">
	  <div class="container">
      <div class="navbar-header">
		    <%= link_to "SAGE", welcome_path, class: "navbar-brand" %>
		  </div>
		</container>
		<ul class="nav navbar-nav navbar-right">
		  <% if @user && !@user.new_record? %>
			  <li><%= link_to "Projects", projects_path%></li>
			  <li><%= link_to "Guides", "https://github.com/jacobjfoley/sage/wiki", target: "_blank" %></li>
			  <li><%= link_to "About", about_path%></li>
				<li><%= link_to "Profile", user_path(@user.id)%></li>
			  <li><%= link_to "Logout", logout_users_path%></li>
			<% else %>
			  <li><%= link_to "Guides", "https://github.com/jacobjfoley/sage/wiki", target: "_blank" %></li>
			  <li><%= link_to "About", about_path%></li>
				<li><%= link_to "Register", new_user_path%></li>
			  <li><%= link_to "Login", login_users_path%></li>
			<% end %>
		</ul>
</nav>

<br>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-stacked nav-pills rounded" id="navbar">
  <li><%= link_to "Project Notes", project_path(@project) %></li>
  <li><%= link_to "Objects", project_digital_objects_path(@project) %></li>
  <li><%= link_to "Concepts", project_concepts_path(@project) %></li>
  <li><%= link_to "Statistics", statistics_project_path(@project) %></li>
</ul>

app/views/layouts/_notifications.html.erb
<% if notice %>
  <div id="notice" class="alert alert-success">
    <%= notice %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div id="alert" class="alert alert-danger">
    <%= alert %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SAGE<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag "favicon.ico" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <div class="row">
      <%= render 'layouts/notifications' %>

      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/control.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SAGE<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag "favicon.ico" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'layouts/navbar' %>
      </div>
      <div class="col-md-9">
        <%= render 'layouts/notifications' %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>